### ISSUE TITLE
Editor doesn't load properly after editing a published file

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1064]
Seems like a bug where, after you edit a published graph via the pencil icon, the editor sits there without playing, displaying nothing. On reload, works ok. Most recently had this in Safari, but think i had it in Chrome too.

**Comment by mattatgit** [comment]
this seems to be fixed now so gonna close it

**Comment by mattatgit** [comment]
Just had this problem again (Safari), opening this graph via the edit icon.
http://vizor.io/matt/rocket-button-test/edit

**Comment by mattatgit** [comment]
Getting this problem quite regularly now (files that load for me first time are becoming the exception, and i'm beginning to expect to reload every time i open a file). This morning was on Kaarlo's branch, but happening on all branches for me i think. Any ideas on this one ?

**Comment by fthr** [comment]
Still happening? I'll keep a look out as well, i think it does happen to me sometimes.
