### ISSUE TITLE
360 photo microsite design

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#1067]

**Comment by inDigiNeous** [comment]
What this needs from point of functionality:

- Drag and drop area for file
- Input element for selecting file (I guess we can hide this if we want with some js hackery)
- Progress bar showing upload status

On desktop, file can be dragged, on mobile the method is to tap the input element and then phone will open native image picker depending on the platform.

Here is the current programmer version:

<img width="897" alt="360site_drop" src="https://cloud.githubusercontent.com/assets/1212726/12549791/47f3d11c-c368-11e5-98ff-413a698f4359.png">

**Comment by inDigiNeous** [comment]
Desktop design: https://app.atomic.io/d/8DAbhLLuacLK
Mobile design: https://app.atomic.io/d/ADVNHJbqT8vv

**Comment by mattatgit** [comment]
this is done & implementation ticket is here
https://github.com/vizorvr/vizor/issues/1136
