### ISSUE TITLE
Value change in inactive slot never picked up

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#1071]
1. Wire up as below, with boolean toggle on
2. Set the condition to false
3. Change the number to something else
4. Set the condition to true
Result: old number is used
Expected: new number is used

this is because the slot is marked inactive and the new value for the true slot is not pulled when the number is marked as updated, and when the condition becomes true, the slot is pulled but the number node is no longer updated, so the new value is never pulled

**Comment by kschzt** [comment]
![screen shot 2016-01-19 at 16 20 15](https://cloud.githubusercontent.com/assets/293426/12421180/9fadab42-bec9-11e5-8b35-134265f90575.png)

**Comment by kkananen** [comment]
Fixed by #1134
