### ISSUE TITLE
Several pixel gap at bottom of editor (destroy)

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1093]
![screenshot 2016-01-25 20 10 34](https://cloud.githubusercontent.com/assets/6858525/12546738/f9befaf2-c39f-11e5-947c-dd9ec6497d71.png)

Guess its related to the scroll bar space

**Comment by gmarinov** [comment]
this is the scrollbar of the parent container indeed. 
potentially related #1140

**Comment by kschzt** [comment]
@mattatgit @gmarinov still happening?

**Comment by mattatgit** [comment]
Yep, i still get this @kschzt

**Comment by mattatgit** [comment]
has been fixed.
