### ISSUE TITLE
Set up message broker for transient messages

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#1101]
Currently, transient messages are relayed by the Node process, they need to be relayed by a third party in order to allow scaling a room across multiple backend nodes. 

It's just a simple pub-sub broker. Use RabbitMQ? Build in-house?

**Comment by gmarinov** [comment]
I've heard good things about ZeroMQ (ØMQ). Redis of which I'm a big fan has Disque in progress too.. thought i'd mention.

**Comment by kschzt** [comment]
I've used RabbitMQ before and had serious issues with its database, Mnesia (aptly named)
