### ISSUE TITLE
Move Player UI box towards bottom of screen (mobile + desktop)

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1120]
![ui_position](https://cloud.githubusercontent.com/assets/6858525/12611787/ac0d041c-c542-11e5-8460-b2aa6769a619.png)

**Comment by gmarinov** [comment]
slight issue with this is that iOS landscape reports the viewport to be higher than it is until the user has rotated their device to portrait and back. I tried various places between the pictured and it never reached further than compromise.
