### ISSUE TITLE
Gaze Cursor affected oddly by animation in editor

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1152]
![stutter](https://cloud.githubusercontent.com/assets/6858525/12717012/e866ace8-c938-11e5-9bea-04c945ae81f0.gif)

Not really sure what is happening here

**Comment by mattatgit** [comment]
ok, so i guess this is not a bug. Just the effect of the cursor "falling off" the object as the wing passes it.

**Comment by mattatgit** [comment]
On second thoughts, this probably is a problem. Not urgent perhaps, but yeah if gaze behaves this way, might be difficult to use it on anything that animates.

**Comment by kkananen** [comment]
Not sure what to do with this? We could have e.g a bounding sphere but this could cause problems with being too big.

**Comment by kschzt** [comment]
@mattatgit @kkananen yes, what shall we do with this?

**Comment by mattatgit** [comment]
Good question. I'm not sure how we can fix this actually. It's mainly a problem for objects that are moving & have very thin / small sections. 

Maybe some kind of adjustment for objects with a scale on any axis equal to or smaller than, say, the width of the gaze cursor. 

But then if you consider gazing at planes with effective depth of 0, while on an angle (this behaviour very likely with UI tiles), this could really mess things up.

So yeah, mm. Tough one. @kschzt @kkananen
