### ISSUE TITLE
Fix "flash of untextured content" on file load

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1164]
Remove the flash of invalid texture that flashes on file loading

**Comment by fthr** [comment]
can we get a GIF of this?

**Comment by mattatgit** [comment]
![flash](https://cloud.githubusercontent.com/assets/6858525/12812684/8030cd38-cb87-11e5-8c15-6cee2176f7a9.gif)

**Comment by mattatgit** [comment]
Was thinking, something that will improve this before we fix it (and given that we might be seeing these textures in all sorts of place), we should maybe make the default  / invalid texture _much_ quieter.
Something like this
http://vizor.io/matt/default-texture
Super basic, and dark. Also just wondering, why do we need to have default & invalid textures ? Seems like we see the invalid texture one a lot, in places where you'd expect the default one to be (i.e. loading models whose textures are not fully loaded yet). Can we maybe just have one texture for both ? @kkananen
