### ISSUE TITLE
typo in default graph

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#1170]
environTment settings. see screenshot.

![screen shot 2016-02-03 at 11 51 28](https://cloud.githubusercontent.com/assets/14101296/12781489/9cc92862-ca6c-11e5-83d8-5cab2374e47a.png)

**Comment by kkananen** [comment]
Fixed https://github.com/vizorvr/vizor/commit/b64a305d485258f4972a9b75b5c8d12a60005a8d
