### ISSUE TITLE
Chat messages show incorrectly as "guest" if signing in in the middle of chatting

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1185]

**Comment by fthr** [comment]
Reproduce:
- Log out from Vizor
- Load the default scene without logged in.
- Type something in chat, see how you appear as Guest
- Sign in. Then type something in chat, see how you appear with your own username.
- Sign out, and refresh the page. The thing you just typed now appear as "Guest"

**Comment by mattatgit** [comment]
One should never sing 🎶 in the middle of chat :)

**Comment by fthr** [comment]
LOL
