### ISSUE TITLE
Fix editing from embedded graphs

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1191]
![embed issue](https://cloud.githubusercontent.com/assets/6858525/12837865/b5686982-cc1a-11e5-85d2-7c3068c0d869.gif)

This is happening from a preview of the blog post in ghost (figured be nicer to embed the example file than just link out to it). Not sure if its a Ghost issue or an embed player issue.

**Comment by mattatgit** [comment]
Also do we really need to have play buttons on this ? pretty clunky having the two successive panels for it. (I definitely need to design a V2 of player UI that is much more discreet)

**Comment by gmarinov** [comment]
two issues that I can see
 - embed player issue. 
 - no title and author.

p.s. i'd love a more discreet interface

**Comment by mattatgit** [comment]
yep, once the blog & videos titles are done, this is what i'm onto next (player with UI optimised for desktop & for mobile, and smaller). Be good if we can also display thumbnails as poster frames by default. And maybe have an option for autoplay or not – can think of plenty of cases where you'd want autoplay (like in my blog post or on a discovery site when you go to the full player page)
