### ISSUE TITLE
Publish dialog revamp.

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1230]
- Progress bar
- Icon preview
- Public/private switch

**Comment by mattatgit** [comment]
Prototype:
https://app.atomic.io/d/nC4yDbM6PkgR
Note that the spinner on the "publishing" button should spin :)  – limitations of Atomic for animated elements
Comp file reference: Publish Dialogue 160322_v2

**Comment by gmarinov** [comment]
also #1079 #1178
