### ISSUE TITLE
Improvement WebVR:  Solve how to set GearVR FOV to correct value

### ISSUE THREAD

**Issue by eric-schleicher** [vizorvr/vizor#1243]
I (try to) use the gear VR regularly with Vizor.  There are two ways in which i can use it.  unfortunately neither is a particularly good experience.  

TL;DR
- Normal Chrome: Slow/ Good FOV 
- DEV Chrome: Fast/Bad FOV.

To get it working I generally followed the steps outlines in the following [Reddit thread](https://www.reddit.com/r/WebVR/comments/3mt8t2/using_webvr_with_the_gear_vr_headset/)

Now, I once disabling the GearVR service I can insert the phone and not load the Oculus Home and load a vizor scene in one of two chrome versions browsers with results as outlines below:

##### **Normal** Chrome
The Field of View looks reasonable, but update rate is a bit slow.  i would not advise spending meaningful time in, or in a graph where you need to move your head a lot.  This is a standard-ish cardboard experience.

##### **DEV** Chrome
Speed is radically better, however the FOV/distortion are very pronounced and uncomfortable to move head around in.

I've gone in an manually adjusted the FOV of the VR Camera to good effect by hard coding it in a specific graph, but it's not really possible to do this in other's graphs. of really by editing when on the phone.

Curious whether there is a change (perhaps to webVR boilerplate) or a particular setting that can be used/created  to set the FOV when the webVR detect that the device is S6 in the headset.  Not sure if the WEBvr can tell if the phone is docket.  if not maybe a user setting for particular device(s)?

the webvr boilerplate makes reference to 
`"Distortion correction, enabled in iOS only."`

Having this be set either natively through detection or as a user setting would make mobile demonstrations of Vizor much more effective.

**Comment by eric-schleicher** [comment]
This is a good testing graph for comparing the the distortion in chrome DEV

http://vizor.io/joaomarques/solar-system-03

**Comment by kschzt** [comment]
@eric-schleicher FYI this has been delayed but we'll be working on it soon as we're starting to use GearVR as our primary demoing platform.

**Comment by eric-schleicher** [comment]
Thx for the update.

**Comment by kschzt** [comment]
@eric-schleicher so is this still an issue using the VR Chromium?

**Comment by eric-schleicher** [comment]
Confirmed that FOV is consistent between normal Chrome, Chrome dev and webvr chromium, though I'm a little dissapointed with the update rate on movement.  seems like it's gotten a little slower.  but that just might be me acclimating to desktop VR hardware
