### ISSUE TITLE
User preferences panel and button design

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1289]

**Comment by fthr** [comment]
Need a button for the interface for this, and then the design for the actual panel.

Things that could be there:

-Show chat by default on/off
-Show info tour by default on/off

What else?

**Comment by mattatgit** [comment]
The preferences should be in the User page, where there should be a tab for them. We have a design for this already, though it doesnt contain switches for chat & tour stuff.

The tour splash should really be a bit different though - it should only play like the very first time you use vizor, and then never again. But we should have a template chooser that you could have a preference for showing on startup or not.

**Comment by fthr** [comment]
Closing this then - related to user page revamp.
