### ISSUE TITLE
Nested Patch tooltip title not picked up correctly from md file

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1315]
![screenshot 2016-02-18 23 07 49](https://cloud.githubusercontent.com/assets/6858525/13142964/ceb1d2a0-d694-11e5-9d67-a7647c56039d.png)

should be called "Nested Patch"

**Comment by kkananen** [comment]
The tooltip title comes from the name of the plugin (in
https://github.com/vizorvr/vizor/blob/develop/browser/plugins/plugins.json)
- careful when editing this file though as syntax errors will break
everything :)
ᐧ
