### ISSUE TITLE
assetloader never completes if object is missing

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#1373]
seems to happen on default scene too.

![screen shot 2016-02-29 at 13 14 41](https://cloud.githubusercontent.com/assets/14101296/13396047/556a3028-deea-11e5-97e1-d754b9b0deed.png)

**Comment by kschzt** [comment]
actually it does complete, but there are no assets, so the size is 0. There was another issue though, in calculating the progress when there were errors
