### ISSUE TITLE
New Slider node UI doesn't stretch correctly

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#1375]
Add a slider node
Change the node title to a long string (which makes the UI stretch)
-> rendering looks broken

**Comment by kkananen** [comment]
<img width="261" alt="screen shot 2016-02-29 at 14 32 37" src="https://cloud.githubusercontent.com/assets/1742765/13397329/5b157814-def1-11e5-8645-b20c657e2d5a.png">

**Comment by kkananen** [comment]
Or is that intentional?

**Comment by gmarinov** [comment]
nice find. thanks.
