### ISSUE TITLE
Preloader: Audio file and the loading progress bar don't work together

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1429]
http://vizor.io/fthr/audio-load-test

Try loading that with a slower connection. You'll notice that first the loading bar goes from 0% to 100% quickly, then goes back to 0% while it loads the audio, and then the scene starts.

Correct behaviour: Progress bar should just go from 0% to 100% and then the scene should start immeidately.

**Comment by kschzt** [comment]
this is [now]  invalid @fthr
