### ISSUE TITLE
Player: Enable finger swiping when in non-VR mode

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1432]

**Comment by fthr** [comment]
this seems to work again ...

**Comment by gmarinov** [comment]
which context? the editor player probably has this issue. the player by itself and in the embed should work OK.

**Comment by fthr** [comment]
Figured out what the confusion was here.

Finger swiping horizontally works OK on Chrome on mobile.
Finger swiping horizontally doesn't work on CHROMIUM on mobile.

**Comment by gmarinov** [comment]
@fthr we're in the hands of boilerplate for the swiping I think, @kkananen .

**Comment by kschzt** [comment]
@gmarinov @fthr close?
