### ISSUE TITLE
Undo makes rotate tool change into move tool

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1472]
![undo causes rotate tool to change into move tool](https://cloud.githubusercontent.com/assets/6809021/14138584/a0e705b4-f676-11e5-8867-4b1b62274825.gif)

1: Load a scene, select an object. Move tool is selected by default. Hit R for rotate tool.
2: Rotate a bit. Then hit undo.
3: Tool changes back to move tool.

Correct behaviour: Don't undo the tool selection, just the rotation.

**Comment by gmarinov** [comment]
this happens because the modify mode is also governed by the modifier keys, so pressing cmd+z or ctrl+z results in also changing the modify mode.
