### ISSUE TITLE
Fix drag uploading issues

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1488]
Trying to upload a complex .obj that is having problems and getting this unclickable error dialogue with an overlay on top of it.

![screenshot 2016-04-05 12 55 19](https://cloud.githubusercontent.com/assets/6858525/14277872/bd63a970-fb2d-11e5-8e59-13426388f907.png)

**Comment by mattatgit** [comment]
Same problem here i guess. We need a cancel button here.
![spinner](https://cloud.githubusercontent.com/assets/6858525/16477211/1ede802e-3ed3-11e6-8054-359b88c1a785.gif)

**Comment by mattatgit** [comment]
Something like this:
![image uploading](https://cloud.githubusercontent.com/assets/6858525/16477370/547d4d40-3ed4-11e6-8b99-24bb8febdace.png)

**Comment by kschzt** [comment]
@mattatgit do you have the complex OBJ somewhere for reference? probably something errors out and doesn't come back

**Comment by mattatgit** [comment]
@kschzt No, sorry, not sure which one that was. I've tried a fairly wide range of objects, but don't have any really complex ones to hand right now. But pretty much anything i upload usually has problems.
