### ISSUE TITLE
dependency graph re-evaluation issue

### ISSUE THREAD

**Issue by uucidl** [vizorvr/vizor#15]
see example:
http://create.vizor.io/uucidl/draw_scaled_image/edit

In this sketch I have a texture fed into a graph that will render it to the framebuffer

After you load the sketch for the first time in your browser, and you press play, nothing is shown.
Press edit into the draw_image subgraph. You will see the texture resolution is read as 0x0
Now press stop and play again, the texture resolution is now 512x512 and the picture shows.

**Comment by kschzt** [comment]
I'm not sure this is happening anymore, I haven't seen the effect of this lately. Closing for now, but if anyone sees this with particular steps, please feel free to reopen.
