### ISSUE TITLE
Preview images for Twitter/Facebook

### ISSUE THREAD

**Issue by amieehibbert** [vizorvr/vizor#1550]
Twitter and Facebook links are not appearing with preview images, as expected.

- Pasting a Vizor.io link into Twitter should use Twitter cards and result in a preview image appearing. 
- Pasting the link now only shows a link: https://www.dropbox.com/s/8ygn9jj8eeylqch/Screen%20Shot%202016-04-13%20at%2012.28.23.png?dl=0

- I'm not sure how Facebook determines preview images, but pasting a Vizor.io link there now results in only a text link: https://www.dropbox.com/s/24vun31vyhu0liu/Screen%20Shot%202016-04-13%20at%2012.29.00.png?dl=0

**Comment by gmarinov** [comment]
![screen shot 2016-04-15 at 14 06 02](https://cloud.githubusercontent.com/assets/14101296/14562172/16017fac-0313-11e6-8a29-cdaba50bac7c.png)

+

![screen shot 2016-04-15 at 14 06 47](https://cloud.githubusercontent.com/assets/14101296/14562185/366f5778-0313-11e6-8d97-83ab8dcd25fb.png)

after a couple of seconds however it became this

![screen shot 2016-04-15 at 14 07 47](https://cloud.githubusercontent.com/assets/14101296/14562210/4e8a83f0-0313-11e6-9e5a-426fb7414a0b.png)

so Facebook catches up eventually, but the first share would go out without the image :|

The png in question is 730kb, so we might need to look into serving a smaller "fast-food" version or from a CDN. We might anticipate such "internet-weather" issues on Twitter too.
