### ISSUE TITLE
Player wobbly on iPhone when swiping down

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#1612]
1. Open vizor.io front page
2. Pull down slightly on the page

Result: the rendering is wobbly (with too many resize events?)
Expected: rendering should be stable

**Comment by gmarinov** [comment]
yes, unfortunately due to a bug in how iOS repaints the elements (tore a lot of hair there), after scrolling there is one additional resize event. zooming to 1.1 is quite heavy-handed (1.01 should be sufficient), it becomes obvious.
