### ISSUE TITLE
Enter VR button not always shown for Vive/Rift

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#1616]
This is probably a race condition, but when it doesn't show, I've been able to get it to show by using the "[x] Disable Cache" option in the Network tab in the Chrome Debugger.

**Comment by eric-schleicher** [comment]
I found that i can ensure the VR button to show consistently by pubishing
the graph (from edit).

Otherwise would not show when opening graph from user page.

**Comment by kschzt** [comment]
@eric-schleicher I'm unable to reproduce this anymore. Are you?

**Comment by eric-schleicher** [comment]
Sorry this slipped by unnoticed.   Will try again.

**Comment by eric-schleicher** [comment]
Woot!
