### ISSUE TITLE
links to vizor chat slack link without http:// come out silly

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#1638]
e.g. type in vizor.io in slack and vizor.io|vizor.io comes out on the other side, see screenshot below

**Comment by kkananen** [comment]
<img width="255" alt="screen shot 2016-05-04 at 16 25 04" src="https://cloud.githubusercontent.com/assets/1742765/15019223/1a6102e6-1215-11e6-9eb9-f40811db7850.png">

**Comment by esaruoho** [comment]
Seems like we disabled the chat a while back, so closing this ticket.
