### ISSUE TITLE
.obj loading: normalise .mtl name in obj

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#1658]
Currently we try to find a .mtl with the same name as the .obj with only the extension replaced but this is often not correct.

We should read the mtllib field from the .obj and search for that name instead

**Comment by kschzt** [comment]
@kkananen how about we remap and normalise the assets inside the obj zip, rename the mtl, change the paths in the mtl, as we need to convert TGA's to PNG anyway, and it would be good to be able to analyse and normalise at the mtl level.
