### ISSUE TITLE
Roomscale: Camera placed at 0, 0, 0 starts at eye level

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1674]
Roomscale problems: http://vizor.io/fthr/floor-on-the-floor/edit

It's just a floor at 0 y position, with camera starting point set at 0, 0, 0, which is how we used to setup roomscale - camera should be placed on the floor on start.

But now, what happens is that ... Camera starts at eye level of me standing up.

**Comment by kschzt** [comment]
was a room calibration issue.
