### ISSUE TITLE
Game pad + Oculus + XBox controller gives TypeErrors

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1699]
This is with Oculus Rift + XBox controller + Game Pad patch:

1) Open ChromiumVR
2) Open default scene in edit mode
3) Add game pad patch
4) add a "Float debug" and connect it to "Left trigger".

Observe how the clock runs very fast, and if you open the console you see lots of TypeErrors.

**Comment by kschzt** [comment]
Looks like the `buttons` array is empty in VR Chromium. Raised Chrome issue - https://github.com/toji/chrome-webvr-issues/issues/66
