### ISSUE TITLE
Add a link to terms of services to 360 site

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1734]
the 360 site needs a link to the TOS. 

We could add it next to the Vizor logo on the bottom?

**Comment by mattatgit** [comment]
![screenshot 2016-06-24 20 32 22](https://cloud.githubusercontent.com/assets/6858525/16335593/d5262324-3a4a-11e6-99ce-3a7a86f8fa39.png)
I would put it behind the ? icon at top right. Then have a simple modal overlay that has a little bit about the site, plus the TOS.

**Comment by mattatgit** [comment]
![screenshot 2016-06-28 09 15 57](https://cloud.githubusercontent.com/assets/6858525/16398844/f118589a-3d10-11e6-90f7-70fb39cd386e.png)
Simpler solution, add the icon above with rollover "Terms", link directly to the crappy google doc
Icon is in the same Sketch file "Extra_TOS_icon" in Dropbox.

**Comment by mattatgit** [comment]
Mmm, that will just be confusing. Let's just go with 12pt text link, like so
![screenshot 2016-06-28 11 32 18](https://cloud.githubusercontent.com/assets/6858525/16401036/365e5658-3d24-11e6-9617-b4765f2aa1dd.png)
