### ISSUE TITLE
Add inertia to (360) player

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1787]
Autorotation will need a ui on/off button. 
Inertia should just be added by default to everything in the player when on desktop.

**Comment by fthr** [comment]
These are two tickets. Let's keep this one for inertia only.

**Comment by fthr** [comment]
Autorotate needs design (where and how does the user turn it on).

Inertia is more straightforward. For me, kuula.co has got it down pretty well: https://kuula.co/post/7fz25

**Comment by mattatgit** [comment]
Yeah Kaarlo has already made a working demo of it in Vizor, which is quite nice. Agreed that Kuula's version is about the sweet spot for speed, acceleration.

**Comment by fthr** [comment]
Duplicate of #1899
