### ISSUE TITLE
Use consistent naming in Properties panel

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1823]
![screenshot 2016-08-10 11 43 20](https://cloud.githubusercontent.com/assets/6858525/17539265/36caeba4-5ef0-11e6-855c-543aabec8fce.png)

If we have to keep this weird tab in the UI, it should at least be consistent with every other mention of the VPL e.g. Node > Patch. Explanation > Select a patch to see its properties.

**Comment by gmarinov** [comment]
but a patch is a collection of nodes. This functionality relates to a single node.

**Comment by mattatgit** [comment]
Well no, in common user parlance, a patch is the basic unit of the VPL. There are various types eg nested patches etc.

**Comment by gmarinov** [comment]
keeping this. as discussed
