### ISSUE TITLE
Decouple UI creation away from plugins

### ISSUE THREAD

**Issue by juho** [vizorvr/vizor#187]
Plugins should create generic UI objects that we provide instead so we don't have DOM creation inside a plugin. Maybe something super automatic based on the values and inputs/outputs in a plugin.

Custom graphics and stuff need consideration. Things like color picker are used once. Also packaging any external UI creation code with the plugin should be possible, so maybe we should look into having a JSON state machine to create and validate UI schemas.

**Comment by gmarinov** [comment]
many plugins do not create a UI, only define io slots and codebehind.
plugins that want to create a plugin UI are  still allowed to do so
the outer shell UI (node UI) is abstracted away and now plugs on top of the graph node (e.g. node-ui.js)
