### ISSUE TITLE
New hotkey for "show graph of the selected object"

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1891]

**Comment by kschzt** [comment]
@fthr what is the new hotkey?

**Comment by fthr** [comment]
ah sorry, the description of this somehow got deleted.

My suggestion would be the key that's to the left of number 1, which is § on finnish keyboard. But it's problematic because that key varies wildly on different keyboards. So i'm open to suggestions.

**Comment by gmarinov** [comment]
@fthr i suggest Shift+Tab for this, it was previously used to show or hide the patch editor, but since by design "build" and "program" are determined by the noodles' visibility, this has been freed to use for this purpose.
