### ISSUE TITLE
Shortcut dialogue text is misaligned due to line break

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1915]
Meaning you can't tell which shortcut is which (in Chrome), due to "Orthographic Camera" breaking over 2 lines.
![screenshot 2016-09-10 16 57 11](https://cloud.githubusercontent.com/assets/6858525/18408597/d31e12a2-7777-11e6-8ce2-29a154510898.png)

**Comment by esaruoho** [comment]
@mattatgit I tweaked the shortcut help desk, and posted a  pullrequest #2012 - check this image for my alterations -- now all text for each shortcut is on the same row as the shortcut key (box):
<img width="456" alt="ka___vizor" src="https://user-images.githubusercontent.com/4966687/27760232-0da2fcf2-5e4b-11e7-93bb-eb7eb0d581f1.png">

also added "Handy Keys" descriptions.

**Comment by esaruoho** [comment]
Also "Toggle Local Handles" wrecks stuff even further. I switched "Orthographic Camera" to "Orthographic Cam", and "Toggle Helpers" to "Helpers", "Toggle Local Handles" to "Local Handles"

This is all in PR #2012 - but I'll probably isolate the Toggles to a separate segment of the help.

**Comment by mattatgit** [comment]
@esaruoho it will be too long for almost all screens if it stays in 2 columns. It should go wider rather than long ie break across into 4 columns rather than stay in 2 massive long columns.

**Comment by esaruoho** [comment]
@mattatgit looks like there's a div class used "twocol clearfix" - i looked at core.less and site.less and found a threecol but wasn't immediately apparent to me as to what to do. Not much of a CSS buff. Maybe @georgi would know?

**Comment by esaruoho** [comment]
Closed by #2018
