### ISSUE TITLE
Distorted play button appears on mobile player

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1926]
![img_0787](https://cloud.githubusercontent.com/assets/6858525/18572375/1af45f16-7bfe-11e6-84e7-fdf021ae19ba.jpg)

**Comment by fthr** [comment]
Hmm ...  i see the play button flash by while loading on Android. But it's not distorted. Did you try to clear cache?

**Comment by mattatgit** [comment]
i still get it in Incognito mode, so i guess clearing the cache won't make much difference

**Comment by gmarinov** [comment]
Confirmed. There are other subtle issues with those icons and their colours, which I hope to address in one pass.

**Comment by esaruoho** [comment]
I get this on an iPad Pro or an iPhone, at times.

**Comment by esaruoho** [comment]
proof
@gmarinov do you still hope to address the subtle issues with icons + colours in one pass?

![new note](https://user-images.githubusercontent.com/4966687/28067399-d7bfedd2-6649-11e7-90e8-5c7a9943c79e.jpeg)

**Comment by gmarinov** [comment]
this has been fixed in an upcoming build.
