### ISSUE TITLE
lists private examples

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#1941]
but only if logged in. if not, it doesn't.

![screen shot 2016-09-26 at 14 39 54](https://cloud.githubusercontent.com/assets/14101296/18836246/0cde762c-83f7-11e6-8590-43890755a6bf.png)

![screen shot 2016-09-26 at 14 41 14](https://cloud.githubusercontent.com/assets/14101296/18836281/3b43f442-83f7-11e6-905b-74415637318d.png)

**Comment by kschzt** [comment]
because you're admin
