### ISSUE TITLE
tweak to /matt/hmd-bake-spinner

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#1948]
please modify this scene's VR camera nested patch to include the boolean toggle:

<img width="641" alt="screen shot 2016-09-29 at 14 52 52" src="https://cloud.githubusercontent.com/assets/14101296/18952903/ca163ca4-8643-11e6-98f2-4dbb9b0ec78b.png">

... and resave. The camera should then stop responding to panning/motion.

**Comment by mattatgit** [comment]
done
http://vizor.io/matt/hmd-bake-spinner
