### ISSUE TITLE
[help] HTC Vive hmd interaction logic at player page

### ISSUE THREAD

**Issue by chenkaiC4** [vizorvr/vizor#1968]
hello, :grinning:,I got some problem. Vizor is a super amazing project. I have started using vizor for twice development a few weeks, but I just don't know HTC vive how to interact with vizor at player page. The page will rotate as I swing the HTC vive hmd.

However I want to send the position and rotatation data to the server to async with other clients.
It seemd that it go through some underlying browser api, but i don't find what it is.

Somebody give me some suggestion? Thanks very much!

**Comment by gbentley** [comment]
Hi Chenkai, Vizor accesses the [WebVR](https://webvr.info/) and [GamepadAPI](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API). The best way to get help is via the [Slack channel](https://vizorvr.slack.com), and to look at existing projects, such as http://vizor.io/lintu/beach-drums-21 or http://vizor.io/gbentley/htc-vive-controllers-rotate-ball-copy . 

Hope that helps!  If so, please close the issue.

**Comment by chenkaiC4** [comment]
@gbentley thank you very much. I have done it, just like you suggestion, the `VRController.js` have the lower api。
