### ISSUE TITLE
Two fixes needed for Patches site

### ISSUE THREAD

**Issue by esaruoho** [vizorvr/vizor#2037]
# 1) User goes to https://patches.vizor.io/browse 

**_Expected result:_**
User sees Patches -text on the top-left-corner.

**_Current result:_**
User sees Vizor-text on the top-left corner.

![vizor no patches no patches no vizor](https://user-images.githubusercontent.com/4966687/28666141-d3ac14b4-72ce-11e7-93b7-d08378ed41f8.gif)

# 2) User enters http://patches.vizor.io with Safari

**_Expected result:_**

User sees "Create WebVR experiences without writing code"

**_Current result:_**
<img width="864" alt="patches_ _explore__create_and_publish_vr_on_the_web" src="https://user-images.githubusercontent.com/4966687/28665874-cd7b192e-72cd-11e7-842a-22fde2783cf1.png">

**Comment by gmarinov** [comment]
5e7fc9e
