### ISSUE TITLE
Create map of all shortcut keys

### ISSUE THREAD

**Issue by wd-vizor** [vizorvr/vizor#234]
This is a general purpose ticket to track all mapped shortcut keys. It should be closed as soon as @mattatgit is satisfied with the mapping (and posts it here definitively).

**Comment by mattatgit** [comment]
Have begun this. Still in progress & will need to develop as we add features, but these are my suggestions so far
https://github.com/vizorvr/vizor-create/wiki/Keyboard-&-UI-Shortcuts
