### ISSUE TITLE
Full review/update of all tooltip copy for Plugins

### ISSUE THREAD

**Issue by wd-vizor** [vizorvr/vizor#256]

**Comment by wd-vizor** [comment]
https://etherpad.mozilla.org/ZrIm7QNBny

**Comment by kschzt** [comment]
@mattatgit can we close this yet?

**Comment by mattatgit** [comment]
Not yet – we still have to write new copy for all of these, including the new ones as they're made.
Hard to do it until we know what patches we are going to have.

**Comment by esaruoho** [comment]
@mattatgit what's the situation with this ticket nowadays? I can push changes to the documentation of the patches/atoms, but I don't know what to write myself - I'm not sure I'd necessarily be good at coming up text to describe the function of the atoms.

**Comment by mattatgit** [comment]
@esaruoho I don't really know. As i recall, most of the tooltips were pretty much dense technical jargon, and mostly gave users no real clue as to (a) what the patch does or (b) how to use it. Along with writing proper docs, this is another one of those large efforts that would require at least 2 people + substantial time. Someone needs to go through and rewrite them all, consulting with Antti when a patch's function or purpose is unclear.

**Comment by esaruoho** [comment]
closing and recreating this ticket as a more realistic one (#2022) - first focus on worst offenders, then to the whole rewrite.
also, this.desc (referenced by wd-vizor) is not the same as /vizor/documentation/browser/plugins/pluginname.md --
