### ISSUE TITLE
Orbit camera preset

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#282]
We need a good orbit camera style preset for the three build, similar to the orbit camera we had in the old version.

**Comment by fthr** [comment]
This is badly needed - hard to test without it. I tried to create one from the old preset, but it didn't work out as it used to.

**Comment by fthr** [comment]
Here's what i'm talking about:
http://vizor.io/fthr/orbit-camera-preset/edit

This should be plugged into the VR Camera ...

**Comment by kschzt** [comment]
obsoleted by new cameras
