### ISSUE TITLE
Errors uploading the kity5.obj (destop object)

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#313]
1: Open this graph http://destroy.vizor.io/fthr/obj-uploader-example/edit
2: Hit the "change" button to upload an .OBJ file
3: Upload kity5.obj file (found in flowdock). If that already exists in your database, rename it and upload.
4: console gives a bunch of errors when you hit OK. See screenshot.

**Comment by kschzt** [comment]
@fthr unable to reproduce. got steps?

**Comment by fthr** [comment]
![obj upload errors](https://cloud.githubusercontent.com/assets/6809021/9632338/43b4232c-518f-11e5-9b90-6870aab39613.jpg)

**Comment by kkananen** [comment]
three.js (and webgl) have a limit of 65k vertices. the error could be nicer though. we should pre-validate the .obj when uploading and perhaps not allow if it's oversized.

**Comment by kschzt** [comment]
closed for inactivity, also there are other issues about validation
