### ISSUE TITLE
Implement new Patch skin

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#337]
- font 
- color

no functionality changes

**Comment by mattatgit** [comment]
![patch ui](https://cloud.githubusercontent.com/assets/6858525/9882364/1d57cf36-5b89-11e5-8acf-474791c11ec8.png)
Sketch file Patch UI 150915

**Comment by mattatgit** [comment]
ok so can't assign to multiple people. So just gonna mention @imgrby here too & you guys can sort it out :)
