### ISSUE TITLE
Android Chromium: Issues rendering simple cube scenes

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#345]
Test case:
http://destroy.vizor.io/fthr/androidcameratest

On computer, you see a cube with an orange texture that's inside another cube, which has grey dots as texture.

On Android Chromium, you see only the background dots when in normal mode. Headtracking seems to work, but you can't see the orange cube.

 In fullscreen mode the head tracking seems to stop, you only see some static grey dots.

**Comment by kschzt** [comment]
@fthr is this still happening?
