### ISSUE TITLE
Ability to delete files you uploaded

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#360]

**Comment by gmarinov** [comment]
@mattatgit  please provide ui looks for this, then assign to @imgrby ?

**Comment by mattatgit** [comment]
![screenshot 2016-02-23 08 23 00](https://cloud.githubusercontent.com/assets/6858525/13233326/5b7fb524-da07-11e5-9608-8ec6c9e12aaf.png)
Design for this has been around for a while. 
Sketch file ref User Page 151118

**Comment by mattatgit** [comment]
removing as duplicated in 1405
