### ISSUE TITLE
Implement Asset Browser

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#420]
Presumably this will have to wait until @kschzt has enabled private assets, but putting it here so we have stuff queued up and ready to move.

![asset browser](https://cloud.githubusercontent.com/assets/6858525/9890031/71f1291a-5bb2-11e5-9304-39dbe6b53fe9.png)

There is a prototype of it here
https://beta.atomic.io/d/upE7d5cfx1c5

If you have any questions about this @imgrby please ask me.
Sketch file reference Vizor Asset Browser 150915_M

**Comment by imgrby** [comment]
leaving in progress until we have actions to make it live
