### ISSUE TITLE
Search: getting multiple results searching the same thing

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#426]
See screenshot. "Slider" shows 3 times.

Full reproduction TBC.

**Comment by fthr** [comment]
![vizor_bug_search_results_3_times](https://cloud.githubusercontent.com/assets/6809021/9902066/54fad9ec-5c74-11e5-8c28-f31c32f9ea8d.png)

**Comment by kschzt** [comment]
@fthr steps to reproduce?
