### ISSUE TITLE
Texture with UV modifier doesn't load correctly

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#427]
Load this scene:
http://destroy.vizor.io/fthr/riding-a-flamingo/edit

The floor texture should be a metallic grid with round holes. However, on load, it shows as a grey gradient.

Stop/Play displays the corrext texture.

**Comment by fthr** [comment]
This still seems to happen in destroy:
http://destroy.vizor.io/fthr/pt11/edit

That should have a round metal hole texture as background. On first load it doesn't show. Tested on desktop and Android Chromium.

**Comment by kkananen** [comment]
never ending. this is still broken in http://destroy.vizor.io/kschzt/pt13 - the floor should be blue.
