### ISSUE TITLE
Chat window tweaks – resize + padding

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#436]
Make chat window vertically resizable.
Also, add correct padding on RHS of chat window (same as on LHS)
See image below for problem (text continues out to window edge without breaking)

![chat no padding](https://cloud.githubusercontent.com/assets/6858525/9919383/5a287200-5c81-11e5-8fc4-8ab3530933c3.png)

**Comment by imgrby** [comment]
padding at the right side can still be little bit wrong due to decision to use native scrollbars which have different width in different browsers. but in chrome it's gonna be alright
