### ISSUE TITLE
Text input box sometimes collapses after editing text

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#441]
![collapsing text box](https://cloud.githubusercontent.com/assets/6858525/9920558/15527f5a-5c8a-11e5-9b6c-2d073740b50b.png)

**Comment by gmarinov** [comment]
the current look box deals better with this but textarea node boxes on the whole have sizing issues.

**Comment by gmarinov** [comment]
![screenshot 2015-11-20 23 05 40](https://cloud.githubusercontent.com/assets/14101296/11299531/6a39fbec-8f7f-11e5-8c39-abbb2feb47d1.png)
