### ISSUE TITLE
Preset/Plugin list: give a CSS difference to the preset and plugin lists

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#456]
There are 2 parts to this list on the left hand panel. The first part comes from presets.json and the other comes from plugins.json

CSS should be able to separate between the two, and make the background color of the presets.json stuff 7 shades of grey lighter (for example).

**Comment by kschzt** [comment]
does this need to be done before newui?

**Comment by kschzt** [comment]
not valid for newui
