### ISSUE TITLE
Some 3D objects in three.js format don't load correctly

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#457]
I've been uploading animal objects from the "Ro.Me" repository (same where flamingo comes from).

A lot of the files do upload but give errors in the console:
Uncaught SyntaxError: Unexpected token /

Here is a file you can load to see the error:
http://destroy.vizor.io/fthr/broken-three-js-object/edit

**Comment by kschzt** [comment]
take a look at the JS you uploaded, http://destroy.vizor.io/data/scene/stork/stork.js, it contains the model inside a JS variable instead of just having the file be the model as JSON. make sure the models don't contain code but are just pure json and it'll work
