### ISSUE TITLE
Implement New Sign in / Sign up dialogues

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#458]
https://app.atomic.io/d/YYg9HwdfeVka

![sign up](https://cloud.githubusercontent.com/assets/6858525/9944485/78a0893c-5d3c-11e5-8708-4a8be76ea3e8.png)

We haven't really finished designing this (ie error handling etc), but it would be good to get code going for it seeing as @imgrby needs things to go on with.

I'll get Saori to update this issue with design as she puts them together today.
The Sketch file to refer to is currently Vizor Signup/Login/Welcome views 150917 but this may change as Saori updates things.

**Comment by imgrby** [comment]
more detailed duplicate added later by Saori
