### ISSUE TITLE
Implement Patch Inspector 

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#459]
Again, this is still in somewhat rough design stages, but let's get it going (if possible) and we'll improve it in code.This is the function where you select a patch and hit I or the "patch inspector" button on the UI and can rearrange slots and access patch preferences (texture sizes etc) This is going to have to be co-ordinated with @gmarinov 's work on the patch UI, but thought i'd cue it up so @imgrby has plenty to do.

Sketch file reference is Master Patch Document 150917
![patch inspector](https://cloud.githubusercontent.com/assets/6858525/9944764/41d51f6a-5d3e-11e5-8c3c-9ad0ac0101a7.png)

**Comment by imgrby** [comment]
implemented: window style, including tabs style(i/o/settings) even though they don't exist and won't show up yet; inputs labels and icons; footer buttons styles. 
tabs and their content should be somehow implemented in graph.plugin.js  > open_editor function, so they sent to bootbox and then work the same way as Assets library tabs. don't want to touch it while Georgi works somewhere close to this. 
soon on newui. 
TODO: some kind of 'sortable' for slots order when there's something to sort.
