### ISSUE TITLE
Implement New Sign in / Sign up dialogues

### ISSUE THREAD

**Issue by Saorikaji2** [vizorvr/vizor#466]
I updated the sketch file called "Vizor Signup/Login/Welcome views 150917" and also I made a mock up animation as a reference for them.

- Sign in (click the sign in to Vizor button to see error )
  https://app.atomic.io/d/fto20eIvXCP6

- Sign up (please click each box to see the little animation for enter the text, also we are thinking of the "create na Account" button should be change to blue when new user fills out all info correctly)
  https://app.atomic.io/d/YYg9HwdfeVka

- Sign up error (click the Username box twice, then you can see how to error message appear )
  https://app.atomic.io/d/TjjrD4Y3bXgF

**Comment by imgrby** [comment]
also requires implementation of account button and dropdown in top bar. (it's presented in design, just a note)

**Comment by imgrby** [comment]
also implemented: forgot password template, reset password template, first time modal design, js actions and ajax call to currently not existing '/checkusername' as 'already taken' message required by design.
