### ISSUE TITLE
Complete types for Plugins (was add types for Patches - Plugins & Presets)

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#479]
Something to use to classify plugin types and show them in different colors in the UI

`<georgi> a "type", especially something that corresponds to a collection in core like E2.dt would be fantastic`

**Comment by gmarinov** [comment]
these will initially be used to set css classes in UI (e.g. slots are categorised as per core.datatypes).

**Comment by kschzt** [comment]
So what you've done to work around the lack of this seems good enough for now, just place it in E2.core, and have plugins and presets map to those. 

![screen shot 2015-09-28 at 19 14 16](https://cloud.githubusercontent.com/assets/293426/10144546/15cdcd20-65d3-11e5-8297-d7b180d0a4a7.png)
