### ISSUE TITLE
New nodes sometime spawn slightly outside the scrollable canvas area - find root cause

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#484]
.. and cannot be dragged into the window (unless selecting all nodes and dragging the whole set down)

to repro:
create a node, such as 'lamber material' through the right-click menu

doesn't happen 100% of time but is frequent

**Comment by gmarinov** [comment]
sometimes they get -98 for their Y position. I have made their UI class to force positive values for now but generally this is either a hardcoded or an incorrectly computed value elsewhere in code.. Will keep an eye on this.

**Comment by kkananen** [comment]
I'm getting this all the time when creating nodes through the right-click menu

**Comment by gmarinov** [comment]
nodes spawn at the wrong Y, which must be due to the new UI taking up some pixels from the top, and seems it isn't accounted for correctly.

**Comment by gmarinov** [comment]
so the right click menu is too tall and doesn't store the position of the original click i think, instead it tries to put the new plugin near its top, or at least the assumption is that its top would be somewhere near the original click.
additionally e2.app applies an unnecessary offset to the position it has been supplied to (which isn't its responsibility).
