### ISSUE TITLE
Hook up UI buttons to hide/show Asset & Patch Libraries

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#487]
I thought i'd already made a ticket for this but couldn't see it & buttons don't work, so here's another.

**Comment by imgrby** [comment]
If you mean top bar buttons to hide/show assets and presets - ticket was done, it's just 'newui.vizor.io' updated long ago.

**Comment by mattatgit** [comment]
ok, so those changes just haven't been pulled into the newui branch yet ? Because they don't work on current http://newui.vizor.io

**Comment by imgrby** [comment]
Yep, newui is not yet deployed from latest git

**Comment by mattatgit** [comment]
ok, got it.

**Comment by imgrby** [comment]
here we go: https://waffle.io/vizorvr/vizor/cards/55f9e6f3f99e9a0300f6a0e5
