### ISSUE TITLE
Image from URL loses connection when copypasting between graph-levels in some cases

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#49]
Reproduce:

 1) press 8 to get a new image displayed, press play
 2) cut the "load image from URL" from the root and paste it inside the image subgraph
 3) connect the "load image from URL" instead of the input proxy 
4) go to root, observe missing image.

no errors in the console.

**Comment by kschzt** [comment]
confirmed, still happening

**Comment by kschzt** [comment]
closed as obsoleted
