### ISSUE TITLE
Graph broken with one drag

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#501]
1. Open editor default
2. Drag one node
3. Reload

Graph is broken. ERROR: Failed to resolve node(qflZidzjtnQX) in graph(root)

**Comment by gmarinov** [comment]
... but if you double click a node to rename it, graph will reload next time.

**Comment by gmarinov** [comment]
also if you just double click a node to rename it and press enter without renaming it, the graph reloads fine. maybe just not saved correctly on that first drag?

**Comment by kschzt** [comment]
this is because for some reason, the snapshot doesn't happen although it's pending. now waiting on #555
