### ISSUE TITLE
WebSocket through proxy connection issue

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#502]
WebSocket connection isn't working through Squid proxy, though WS echo service works.
```
@kschzt @Vizor_VR Chrome spits this: "failed: Establishing a tunnel via proxy server failed." and FF : "Sec-WebSocket-Protocol:undefined"
```
https://twitter.com/TobozoTagada/status/646710533731782657

**Comment by tobozo** [comment]
Without this tunneled proxy I'd be unable to use web sockets.
The squid is accessed through SSH tunneling (local:3128 <=> proxy:3128), here are some of my squid.conf settings, maybe one of those is making the wss connexion fail ?

acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl Safe_ports port 70          # gopher
acl Safe_ports port 210         # wais
acl Safe_ports port 1025-65535  # unregistered ports
acl Safe_ports port 280         # http-mgmt
acl Safe_ports port 488         # gss-http
acl Safe_ports port 591         # filemaker
acl Safe_ports port 777         # multiling http
acl CONNECT method CONNECT
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_port 3128 transparent
cache deny all

**Comment by kschzt** [comment]
@tobozo and in your OS settings, do you have an explicit proxy set up to localhost:3128?
<img width="574" alt="screen shot 2015-09-28 at 10 20 43" src="https://cloud.githubusercontent.com/assets/293426/10142988/a03acfc0-65ca-11e5-94ba-a121ee3a0388.png">

**Comment by kschzt** [comment]
@tobozo just an update, this is getting pushed down in priority due to a deadline on Oct 6, but I will get to this as soon as I can. Any more info on your local setup is appreciated. I wonder, is the proxy eating the Cookie header?

**Comment by tobozo** [comment]
Yep proxy is declared system wide (Windows 10).
If Cookie Header test implemented on this page http://www.websocket.org/echo.html ?
All tests work fine in all browsers with my current proxy configuration.

**Comment by tobozo** [comment]
Just stumbed upon this : http://www.scip.ch/en/?vuldb.78130 getting closer ?

**Comment by kschzt** [comment]
I'm closing this. It can't be fixed by us, without going to WSS, which we'll do in another ticket (#1260). Your best bet for the time being is to use a VPN that doesn't have a MITM proxy.

**Comment by kschzt** [comment]
@tobozo this has now been fixed :) sorry for the delay. we're now using secure websockets by default
