### ISSUE TITLE
Wrong breadcrumb separator. again. newui

### ISSUE THREAD

**Issue by imgrby** [vizorvr/vizor#509]

**Comment by mattatgit** [comment]
![breadcrumb](https://cloud.githubusercontent.com/assets/6858525/10090576/6c066730-6374-11e5-9edc-7ac0a12ec7af.png)
here's the correct one. Sketch file ref Vizor Browser UI 150925

**Comment by imgrby** [comment]
hopefully will be fixed on next newui update
