### ISSUE TITLE
replace welcome image

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#514]
because rights

**Comment by mattatgit** [comment]
With this, it will only be shown to brand new users, non-logged in users, so it doesn't need the "create new graph" button because one has already been created, right ?

**Comment by mattatgit** [comment]
![welcome to vizor dialogue](https://cloud.githubusercontent.com/assets/6858525/10274407/2f5494ca-6b89-11e5-9f67-8aa6e27b794a.png)
Sketch file reference Notifications & Dialogues Master 151005
