### ISSUE TITLE
populate fields in account details form

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#515]
name must have current name
username must have current username
email must have current email
username or email must be locked if it can't be changed.

**Comment by imgrby** [comment]
Can't reproduce because cannot login on local.

**Comment by imgrby** [comment]
see waffle 579. added function to fill fields, because template won't render {{user.username}} or {{user.email}} - have to fill them after, both account controller or application.js (where ciustomBootboxTemplate lives) couldn't render layout with these vars.

**Comment by imgrby** [comment]
@gmarinov, @kschzt
