### ISSUE TITLE
username validation on logged-in account popup

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#517]
when logged in and entering the same username as the one I have, an error message appears "sorry this username is already taken"

**Comment by gmarinov** [comment]
this popup needs reviewing as a whole

**Comment by imgrby** [comment]
will fix that. anyway it should check if username is taken, just ignore yours

**Comment by imgrby** [comment]
added own username check. and second thing - as long as we don't have /checkusername for ajax yet - it will still return 'already taken' for any other username than yours
