### ISSUE TITLE
Implement HTML Page Title format

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#520]
Make page title in format " Graphname ⎮ Vizor" when in the editor, for logged in users. When in the Project View, it should be "Projects ⎮ Vizor" for logged in users. For visitors, don't show graph name, just "Vizor". When visiting another user's page it should show "UserName ⎮ Vizor"

**Comment by imgrby** [comment]
@gmarinov, @jaakko need advice here about where to take graphName from

**Comment by imgrby** [comment]
as long as the only graph name we have atm is the E2.app.path - it will be displayed in editor, excluding 'username/'
