### ISSUE TITLE
Update Main Navbar UI

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#521]
![editor ui 150925](https://cloud.githubusercontent.com/assets/6858525/10093198/932e555c-6392-11e5-86be-004e942df9fc.png)
Sketch ref Vizor Browser UI 150925

Grouped all floating window buttons together (Assets / Patches / Chat)
Scale & Rotate still there as they'll be coming soon i guess.

Publish can be removed for now. Edit a copy is Duplicate.
Also have removed the Editor / Patches switch for now.

**Comment by imgrby** [comment]
I'm not sure about removing publich and world editor now, cuz it caused merge conflicts last time.  @gmarinov ?

**Comment by gmarinov** [comment]
this also hasn't got the Patches/3Deditor toggle..

**Comment by mattatgit** [comment]
yeah, as mentioned. We can leave it in if it's going to create merge conflict drama. Just not really happy with it the way it currently is.

**Comment by imgrby** [comment]
can we at least attach editor / patces view calls to bottom right buttons? or is it something different?
