### ISSUE TITLE
plugin converters/matrices_to_camera doesn't load

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#528]
[Error] ReferenceError: Can't find variable: Camera
	dispatch (flux.js, line 209)
	addNode (graphEditCommands.js, line 74)
	execute (undoManager.js, line 59)
	addNode (graphApi.js, line 10)
	createPlugin (application.js, line 117)
	instantiatePlugin (application.js, line 131)
	(anonymous function) ([native code], line 0)
	emitEvent (event-emitter.js, line 380)
	emit (event-emitter.js, line 407)
	(anonymous function) (plugin-manager.js, line 40)
	emitEvent (event-emitter.js, line 380)
	emit (event-emitter.js, line 407)
	callback (contextMenu.js, line 155)
	(anonymous function) (contextMenu.js, line 84)
	dispatch (jquery.min.js, line 3)
	handle (jquery.min.js, line 3)

**Comment by fthr** [comment]
This plugin should be removed from the list  entirely, it's a legacy one.
