### ISSUE TITLE
bugs when connecting arbitrary nested graph output to output proxy

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#531]
create nested graph, edit nested graph
insert output proxy, leave unconnected
in main graph, insert output proxy, insert scene renderer
in main graph, connect nested graph node output to output proxy node 
expected: nodes connect
actual: nodes signal incompatible, no connection is made

connect nested graph output to scene.
grab connection from scene end and reconnect to proxy output node
expected: result consistent with above
actual: nodes connect OK

**Comment by fthr** [comment]
I think this works as expected now.
