### ISSUE TITLE
Polish Patch selection style

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#543]
![selected](https://cloud.githubusercontent.com/assets/6858525/10135313/156ea702-6630-11e5-8baf-8d0f95d674f9.png)

Selection should be #ffffff 1px border.
For basic patch style, let's also remove the drop shadow (and selection glow).

Sketch file ref: Master Patch Document 150928

**Comment by gmarinov** [comment]
safari has an issue with border-radius and display:table that makes the nodes so neat. i've made the nodes display a hard box shadow that mimics the requested border.
