### ISSUE TITLE
patch browser resets size and is not resizable

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#544]
1. open patch library (presets)
2. enter a search that results in a small number of results (e.g. "/")
3. with search results displayed, close patch library floating window
4. open patch library again
5. clear search

expected: normal size window
actual: small window, clearing search does not restore height

version: newui

**Comment by imgrby** [comment]
about "and is not resizable" - if it's required for this window - please add a separate issue to avoid misunderstanding issue-pr. all other things are fixed.
