### ISSUE TITLE
Tab to hide nodes frequently stops working with new ui

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#559]
sometimes comes back after hitting tab ~20 times..

**Comment by gmarinov** [comment]
something happens to that keydown handler so the UI thinks it's focussed in an input somewhere., will debug

**Comment by gmarinov** [comment]
the modal dialog kills events attached to window. because of an issue with bootbox.
application.js and ui js now bind to document.body

**Comment by gmarinov** [comment]
the world editor killed tab last time i tried, when it goes, I find that copy+paste any node restores it.
