### ISSUE TITLE
update controllers/user.js to work with new modals

### ISSUE THREAD

**Issue by imgrby** [vizorvr/vizor#579]
current user.js designed for old fields sets in modals. e.d. theres no 'confirm password' field anymore in Sign Up, but new 'Name' field. so it fails to sign up now.

**Comment by imgrby** [comment]
don't know if me or @kschzt should go there

**Comment by gmarinov** [comment]
@imgrgyb get as close as you can to the model, but if you hit that, then contact @kschzt

**Comment by imgrby** [comment]
sure i already am. need to add user.name and remove passwords fields (there's no confirmation now) comparison - first things to go forward

**Comment by gmarinov** [comment]
do it in the controller, then pass the user's name along with the other data to the model and leave a separate todo for @kschzt .  models/user.js has the schema.

**Comment by imgrby** [comment]
see signup-updates branch
sign in and click userpulldown - account. can render username, but cannot name and email. not clear what's going on there, in account modal. filling data myself, submit form and then some unclear ajax things happen. 
temporary 'return' added in line 99 to skip frontend fields validation to test it

**Comment by kschzt** [comment]
done on signup-updates branch

**Comment by imgrby** [comment]
Sign up. Can input already registered e-mail (somehow we don't have something like /account/emailexists ), but when click "Create Account" obviously it check at back end but cannot show message, console says:
TypeError: err.responseJSON.map is not a function
http://localhost:8000/scripts/account-controller.js
Line 261
