### ISSUE TITLE
unified UI to backend comms

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#595]
UI calls to backend should include UI token ("app id") and a unique identifier (acting like a current "app secret") that isn't the session id. As per discussion these should be in http headers. "Post" or "put" data is, as usual, sent via JSON.

see http://stackoverflow.com/questions/7686827/how-can-i-add-a-custom-http-header-to-ajax-request-with-js-or-jquery for appending custom headers

(also see #596)

**Comment by kschzt** [comment]
dupe of #596

**Comment by gmarinov** [comment]
not a dupe, merely its frontend counterpart
