### ISSUE TITLE
Material modifier bugs out

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#608]
Reproduction:
-Load up destroy in incognito mode.
-Load the default scene (new)
-Add object "3D model" from the presets menu
-Connect it to scene.
-Navigate inside the 3D model subgraph
-Press "Change" and load the model named "Goat.js".
-Add a slot to material editor
-Observe the slot font change to a buggy one (no bullet circle for connecting the node, font too small)

We get this error in the console during the process:

Uncaught SyntaxError: Unexpected token <

**Comment by gmarinov** [comment]
node.rename_ui was modifying directly things it shouldn't
