### ISSUE TITLE
Design a button for "Move" in the top bar

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#617]
The 3D editor has 3 modes:
Rotate, Scale and Move.

Move doesn't have a button at the moment, so it needs to be designed and put into place.

**Comment by mattatgit** [comment]
Move doesn't really make sense as a button, it's quite redundant. By default when in the editor you should be in "select / move" mode. If you use the scale or rotate tool, `esc` key should return you to the standard select /move cursor.
