### ISSUE TITLE
NewUi: Rotate, Scale and Move buttons in the top bar should be "toggle" buttons.

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#618]
These buttons are now clickable as normal,
but the real functionality is a mode toggle.

So when you're in 3D editor, by default it's in "Move" mode, showing you the 3D cursor where you can move your object around.

Clicking "Rotate" should disable the move mode and change the cursor into the "Rotate" cursor.

Same for "Scale".

**Comment by gmarinov** [comment]
resolved in recent commits
