### ISSUE TITLE
Top Bar: Only show relevant buttons, when in different modes

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#619]
So we have 2 modes: The 3D editor mode and the graph editing mode (VR camera).

When you're in 3D editing mode, these buttons are not relevant:  Save patch, inspector, magnifying glass.

When you're in VR camera mode, then the "Scale", "Rotate" and "Scale" buttons are not relevant, and should be hidden.

**Comment by mattatgit** [comment]
I don't agree that they should be hidden. Contextual is good, but having pieces of the UI blank out and then reappear is not a good idea. I suggest we solve this in a different way.

**Comment by imgrby** [comment]
we can disable them the same way we disable playback or view buttons.

**Comment by mattatgit** [comment]
yep ok, if thats what you mean, cool. Lets do that.
