### ISSUE TITLE
Reverse the function of Editor  & VR Camera switches

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#624]
Currently, pressing the VR Camera icon takes me into the Editor cam view (ie it has a grid & i can select & manipulate objects). This behaviour should be fixed. Let's also implement the same style of active indicator we're using for the play pause buttons for the camera as well to show which one is active.

![button style](https://cloud.githubusercontent.com/assets/6858525/10275728/812b9576-6b95-11e5-884f-66c00bceb90c.png)
.
Sketch file ref Vizor Browser UI 151005

**Comment by mattatgit** [comment]
ok, so this is how it should work.
Left icon is editor (work) camera (shows grid)
Right icon is VR (output) camera (no grid)
![cams](https://cloud.githubusercontent.com/assets/6858525/10297129/e0484146-6c1a-11e5-83d0-975307939ea5.jpg)

**Comment by mattatgit** [comment]
This really needs doing before release as it is super confusing

**Comment by gmarinov** [comment]
have reversed the buttons. On defaulting to 3d editor I'd still need to confirm this with the rest of team, I'm not sure if it's sufficiently complete (I don't mean to imply it isn't! I just don't know.)

**Comment by gmarinov** [comment]
advised to default to VR view for now, switch to 3d editor is scheduled..
