### ISSUE TITLE
Texture > Edit > select file > Select doesn't close modal

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#633]
urgent

**Comment by gmarinov** [comment]
[Warning] 900 console messages are not shown.
[Warning] THREE.WebGLRenderer: Texture marked for update but image is undefined  (three.js, line 22460)
Object
[Warning] THREE.WebGLRenderer: Texture marked for update but image is undefined  (three.js, line 22460)
Object

seems to be on every animationFrame

**Comment by imgrby** [comment]
https://github.com/vizorvr/vizor/blob/develop/browser/scripts/file-select-control.js#L234
this one must be removed because the dialog is already appended here: https://github.com/vizorvr/vizor/blob/develop/browser/scripts/file-select-control.js#L172
