### ISSUE TITLE
Windows scrollbar issue

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#636]
This happens on windows only:

1) Browser fullscreen, load a new Vizor file. Shows correctly with no scrollbars. (screenshot 1).

2) Window gets smaller for some reason, and scrollbars are introduced.That's correct, although the bars are quite ugly on windows.
(screenshot 2)

3) Maximize the window back to fullscreen, the scroll bars remain (screenshot 3)
This is incorrect, we shouldn't see scrollbars here.

**Comment by fthr** [comment]
![scrollbars1](https://cloud.githubusercontent.com/assets/6809021/10290245/a58b33ca-6bab-11e5-8490-1cd9d86247e3.jpg)

![scrollbars2](https://cloud.githubusercontent.com/assets/6809021/10290247/a86f7ca4-6bab-11e5-8db8-933ec84b768b.jpg)

![scrollbars3](https://cloud.githubusercontent.com/assets/6809021/10290249/ab4d88bc-6bab-11e5-8aab-796828b97d2e.jpg)

**Comment by gmarinov** [comment]
related: #331
