### ISSUE TITLE
Newly added objects show port as connected when it is not

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#643]
![connected port bug](https://cloud.githubusercontent.com/assets/6858525/10297491/7035f074-6c1f-11e5-9aa9-37727c69921c.png)
This usually happens to me with a new graph and i add a Box object

**Comment by gmarinov** [comment]
newly added (sub-)graphs do this. internally that slot is connected, only it's connected to something else..

**Comment by mattatgit** [comment]
but the 3D output slot is not connected, right ? It has something in the nested patch proxied to the output, but that output is not connected (hence box is not visible). To me, this seems to be clearly a bug. If not, it should be, as it doesnt make sense.

**Comment by fthr** [comment]
This seems to work correctly nowadays.
