### ISSUE TITLE
Cannot login with upper case letters in email

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#664]
We should do case insensitive email matching

**Comment by kkananen** [comment]
We seem to be lowercasing the email addresses when creating an account but not when logging in

create an account with a MixedCaseEmail@domain.com

try to log in - MixedCaseEmail@.. doesn't work but mixedcaseemail@.. does

**Comment by gmarinov** [comment]
- RFC 5321 (2.4) says emails are  case-sensitive@case-insensitive.domain. 
 - some people prefer to use mixed case for their emails and especially their usernames
 - UX-wise we're better off being case-insensitive, especially regarding usernames, but we must never edit the user's information, so the .findOne calls we use should match case-insensitive.

I've taken out all lowercasing and marked the places this needs changing with // #664

**Comment by gmarinov** [comment]
also see #1100

**Comment by kschzt** [comment]
so is this fixed? @gmarinov
