### ISSUE TITLE
Ability to reset camera by pressing R

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#684]

**Comment by gmarinov** [comment]
are we still doing this? @mattatgit @fthr @kschzt

**Comment by mattatgit** [comment]
I hadn't heard of this one. Reset which camera & to what ? My idea is that, if possible, all (single)objects including cams should when selected have 3 draggable, editable values showing beneath them for moving, scaling & rotating via values. Plus maybe a way to zero all the values at once, or individually.

**Comment by gmarinov** [comment]
Properties solves this.
