### ISSUE TITLE
move 'delete account' to user section. was: 'delete account' from useraccount modal does not work.

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#704]
404 Error: Not found: /account/delete

**Comment by gmarinov** [comment]
makes no sense to me to place this in a modal window? 
this being vr on the web, i'd leave it for the userpage (user profile section).  @mattatgit ?

**Comment by mattatgit** [comment]
yes, that's where it should go.

**Comment by gmarinov** [comment]
by "that" do you mean the user section or a modal dialog within the patch editor (like currently)?

**Comment by mattatgit** [comment]
sorry, i probably shouldn't comment on github till i've had coffee :) i meant, it should go into the user page (user profile section) as you suggested.
