### ISSUE TITLE
graph breadcrumb - rename Root to Scene 1

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#723]

**Comment by gmarinov** [comment]
postponed for review

**Comment by eric-schleicher** [comment]
Even though you aren't soliciting feedback on this...  here is some :)   

As a generic/abstract flow based programming environment, not everything at the top level is a scene.  While our uses of Vizor certainly include scene graphs, there is quite a bit that we intend to build that lies entirely outside that domain. in that pattern...  using vizor as an execution/workflow runtime.  my only comment (preference) here is to not restrict the vizor's taxonomy 'just' scene graphs.

**Comment by kschzt** [comment]
+1 to what Eric said.
