### ISSUE TITLE
graph saved with same name as another graph overwrites the previous one without notice

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#729]
1. click publish graph
2. save with the name of an already-published graph

expected one of: 
  - graph saved with a non-conflicting name
  - ask for confirmation
  - "computer says no" (quickest to implement, I vote).

actual:
 graph overwrites previous graph without notice

**Comment by fthr** [comment]
Yes, it would be great to have a dialog "A graph with this name already exists. Would you like to overwrite it? Yes / No"
