### ISSUE TITLE
Got 500 expected 404

### ISSUE THREAD

**Issue by eric-schleicher** [vizorvr/vizor#749]
i'm working on my first plugin, by accident i put the wrong path to a new resource in the template, 

in sorting out what i had done wrong, i discovered that when (in development mode) if you directly request a resoruce that isn't there, you get this 50x instead.

So in this case the url I've entered is incorrect.... but I expected a regular 404.

![image](https://cloud.githubusercontent.com/assets/8261783/10711587/87505c76-7a35-11e5-902f-b101492deee3.png)

**Comment by gmarinov** [comment]
![screen shot 2016-01-07 at 13 36 25](https://cloud.githubusercontent.com/assets/14101296/12171658/a3d10e38-b543-11e5-8d9a-5d0cf4c9ea8f.png)

![screen shot 2016-01-07 at 13 36 52](https://cloud.githubusercontent.com/assets/14101296/12171663/a6e317e2-b543-11e5-854b-7ebeee3062bd.png)
