### ISSUE TITLE
Fix description text on vizor.io links pasted to other applications

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#770]
When pasting vizor.io links to e.g. slack, the description text generated for the link is the default "Vizor lets you create compelling VR content right in your browser" instead of the name of the graph

Jaakko:
yeah, that's in layout/player.handlebars
it's most likely the og:description in Slack's case
that could just have a variable passed to it from GraphController.prototype.graphLanding()

**Comment by gmarinov** [comment]
please provide a sample URL

**Comment by fthr** [comment]
Sample URL: http://vizor.io/joaomarques/hover-make-another-object-smaller

When pasted to Slack it says "Vizor lets you create compelling ...".

**Comment by kkananen** [comment]
Fixed by #1167
