### ISSUE TITLE
Make my current editor camera position the VR camera position

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#835]
So new button in the interface - "Make my current editor camera position the VR camera position". This way you can pan and zoom in the editor mode into a good position, and then have the VR camera jump to that. This is a much easier way than trying to move the VR camera there using its handles.

Added a "design" label here because needs a design for the button and place in the interface.

**Comment by fthr** [comment]
This needs design too.

So new button in the interface - "Make my current editor camera position the VR camera position". This way you can pan and zoom in the editor mode into a good position, and then have the VR camera jump to that. This is a much easier way than trying to move the VR camera there using its handles.

**Comment by eric-schleicher** [comment]
+1  nice feature!
