### ISSUE TITLE
In editor mode, when selecting and object, and then hitting tab, navigate inside the selected nested patch automatically

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#837]
This will optimize the necessity for navigating via root all the time when programming.

So select an object in edit mode. Hit tab. You are magically inside that object's nested graph and you can start changing parameters.

This will make accessing the root a bit harder, but most of the time and most users won't even need to go into root.

**Comment by kschzt** [comment]
resolved by #1819
