### ISSUE TITLE
Implement Social Graph sharing for Vizor.io

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#840]
Image & updated text

new text: Create and share VR content on the web

image:
![social graph](https://cloud.githubusercontent.com/assets/6858525/11292041/573a5da8-8f9c-11e5-855e-dda60b826c73.png)

Sketch comp: social graph Vizor

**Comment by fthr** [comment]
Explanation from Matt: That's facebook's social sharing thing ie at least a title, correct catch copy and a nice image when Vizor is shared. Later, click-drag graph players, but for now just a nice image & text when vizor links are shared.

**Comment by mattatgit** [comment]
This is done.
