### ISSUE TITLE
Update Build/Program window styles

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#843]
![object window](https://cloud.githubusercontent.com/assets/6858525/11297864/4dba2e88-8fcf-11e5-8571-2d3eaa6f26c7.png)

Sketch file ref Vizor UI 151105

In current form, quite confusing as to which tab you are currently on.

**Comment by gmarinov** [comment]
tabs for this have been fixed. (but not yet the rest of looks)
