### ISSUE TITLE
Change default font for in-editor text

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#848]
From Arial (please god, no) to Source Sans Pro

**Comment by fthr** [comment]
For clarity, this is talking about the Shader editor, and other code editors that pop up from patches.

**Comment by mattatgit** [comment]
Actually, no, this one is talking about any text set by the user within VR (in the world editor).
There is a separate ticket talking about using Source _Code_ Pro for the shader editor & any other code editors. But i'm still working on the proper design for that, so will merge those tickets when i'm done.

**Comment by fthr** [comment]
OK. I just tried it, and apparently Source Sans Pro works with the Vizor text patch. Screenshot added so you can confirm. 

If so, this is a very simple change just in the preset. I'm labeling this as preset so I can do the change when I do the next preset fix run.

**Comment by fthr** [comment]
![source_sans](https://cloud.githubusercontent.com/assets/6809021/11810954/eae803aa-a33a-11e5-9141-1808a9b828df.jpg)

**Comment by mattatgit** [comment]
Hard to tell from that text, but probably is.Better also that we set the default text in title case eg "Welcome to Vizor"

**Comment by mattatgit** [comment]
or perhaps we just follow the Sketch.app model –  "Type something". Might be better.

**Comment by fthr** [comment]
http://vizor.io/Y9mnfrUcpNna

seems correct to me.

**Comment by mattatgit** [comment]
yep indeed, we're good now :)
