### ISSUE TITLE
Allow clickless panning around in fullscreen by using pointer lock

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#891]
from @tbalouet

**Comment by mattatgit** [comment]
So capture the mouse entirely ? Is this a good idea ? Mouse capture absolutely enrages a large percentage of web users. Or am i missing the point of this ?

**Comment by gmarinov** [comment]
mousemove doesn't travel enough for a 360 and just imagine if it did. 
vote no.

**Comment by tbalouet** [comment]
Not sure that it enrages users, but maybe I'm mistaken. On the contrary, it's very easy to use, and way more immersive than having to click and drag to see the scene. Plus, you don't have 2D UI on those screens so no need for a mouse there.
Example of how it could look like : http://www.scenevr.com/

**Comment by kschzt** [comment]
@mattatgit @gmarinov so this is for the standalone player in fullscreen, capturing the mouse with pointer lock would allow panning around just by moving the mouse, instead of having to click to pan.

**Comment by mattatgit** [comment]
yeah, the scenevr example above, does that actually do it ? seems like just WASD movement to me. 

My objection is: i hate things that capture the mouse. Vertical scroll capture for example is generally (there are exceptions) a kind a hell on the web to me. If for some reason i'm unwillingly dropped into a fullscreen scene, and my mouse pointer has vanished and moving my mouse just moves the camera without me being able to see any mouse cursor i could use to get out of there, that to me is not good UX. (If this is the behaviour you are talking about).

Giving users the _option_ to do that is fine with me, but forcing it on them, not so good. 
@kschzt

**Comment by tbalouet** [comment]
You can refuse to let the mouse capture operate, the web browser require it
and allow the user to say no, like the fullscreen request

2015-12-02 22:26 GMT+01:00 Matt Innes <notifications@github.com>:

> yeah, the scenevr example above, does that actually do it ? seems like
> just WASD movement to me.
>
> My objection is: i hate things that capture the mouse. Vertical scroll
> capture for example is generally (there are exceptions) a kind a hell on
> the web to me. If for some reason i'm unwillingly dropped into a fullscreen
> scene, and my mouse pointer has vanished and moving my mouse just moves the
> camera without me being able to see any mouse cursor i could use to get out
> of there, that to me is not good UX. (If this is the behaviour you are
> talking about).
>
> Giving users the *option* to do that is fine with me, but forcing it on
> them, not so good.
> @kschzt <https://github.com/kschzt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vizorvr/vizor/issues/891#issuecomment-161438508>.
>



-- 
<http://www.beloola.com>
*Thomas BALOUET @thomasbalou*
* <http://beloola.com/balou>*
*VR CREATIVE ENGINEER @Beloola*
*Tel :* +33 (0)651-886-140

**Comment by gmarinov** [comment]
have decided not to implement this.
