### ISSUE TITLE
Preset: Drag and drop an image.

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#93]

**Comment by fthr** [comment]
Image on screen that user can "pick up" by clicking on the mouse and dragging to another position. When user "drops" it it would stay in that position.  Should be able to have many images on screen at the same time and able to drag each differently.

This can be done by combining the button preset with an image preset somehow, and using Sample and Hold plugin I think. I've tried to do this a couple of times and failed. The latest experiment is at:  http://create.vizor.io/fthr/carousel-with-sample-and-hold-drag-2

**Comment by kschzt** [comment]
@fthr wanna keep this?

**Comment by fthr** [comment]
Nope. This will be covered by the 3D editor. Closing.
