### ISSUE TITLE
Switching between Build & Program with input left in a search field results in empty window

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#944]
Not a terribly hairy bug, but annoying. If you enter text into the search field of Build or Program and then switch, the other panel is blank as it is being filtered by input from the other side.
![switch bug](https://cloud.githubusercontent.com/assets/6858525/11621160/7005f224-9d0d-11e5-95a3-43c0e5b743b2.gif)

Means we also need, in addition to the fix, "clear input" icons so you don't have to manually delete text to go back to browsing

**Comment by gmarinov** [comment]
#855
