### ISSUE TITLE
Add filter options to object load dialog

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#962]
By default three.js json files from clara.io etc contain all kinds of things we don't necessarily want to import, e.g. lights. So we should be able to filter these out of the imported mesh.

Add some option checkboxes to object loading dialog (the file selector):

E.g.
[ ] meshes
[ ] lights
[ ] cameras

These could then be used to filter what gets loaded from the json.

**Comment by fthr** [comment]
I kind of think we should always filter out lights and cameras though - unless those would automatically become Vizor nodes in the graph. Otherwise it doesn't really fit the workflow.
