### ISSUE TITLE
Shadertoy preset should open and present a Shadertoy-compatible template

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#968]

**Comment by fthr** [comment]
A workaround preset can be found here: http://vizor.io/fthr/shadertoy-to-texture/edit

As mentioned by Reiska, this isn't the optimal way to do it - but it's atleast a convenient way for now to get the shadertoy effect into most places one would want.

**Comment by kschzt** [comment]
closing this as there is no shadertoy preset
