### ISSUE TITLE
Ability to delete/hide published projects

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#974]

**Comment by fthr** [comment]
This one should go into Design as well - how does this look to the user and how does it work.

**Comment by fthr** [comment]
This one should go into Design as well - how does it look to the user and how does it work.

**Comment by mattatgit** [comment]
Going to close this one as these are 2 separate issues. There is no "hiding" published projects, but there will be publish & unpublish buttons in the next revision of the user page, which i will add tickets for when the design is finished. Deleting files is part of the same UI, but has its own ticket above.
