### ISSUE TITLE
File browser text does not appear in Firefox / Firefox Nightly

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#982]
![firefox_file_browser](https://cloud.githubusercontent.com/assets/6858525/11861035/19759eb2-a4d0-11e5-98ab-32794cc8936a.png)

**Comment by gmarinov** [comment]
![screen shot 2016-01-08 at 15 00 04](https://cloud.githubusercontent.com/assets/14101296/12200758/90b25520-b618-11e5-8754-8bab4910f090.png)

no fix required.
