### ISSUE TITLE
Display total file size in user page

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#995]

**Comment by kschzt** [comment]
@mattatgit is there a design for this? 

the backend feature is ready for UI @gmarinov, (re-)published graphs will have new fields `stat.size` and `stat.numAssets`.

**Comment by mattatgit** [comment]
@kschzt there's a design for it in the Editor, can't remember if there is one for it in the User Page, will check. We'll also need it in the Publish Dialogue

**Comment by kschzt** [comment]
@mattatgit would you mind pasting the design for this here? thx

**Comment by kschzt** [comment]
done - with #1415
